/**
 * constants.js - Constantes globales del proyecto
 * Logica pura: valores inmutables compartidos entre modulos.
 *
 * Elimina "numeros magicos" del codigo y centraliza configuracion.
 */

// === TIEMPO ===

var MS_POR_SEGUNDO = 1000;
var MS_POR_MINUTO = 60 * MS_POR_SEGUNDO;      // 60000
var MS_POR_HORA = 60 * MS_POR_MINUTO;         // 3600000
var MS_POR_DIA = 24 * MS_POR_HORA;            // 86400000

var SEGUNDOS_POR_MINUTO = 60;
var MINUTOS_POR_HORA = 60;
var HORAS_POR_DIA = 24;
var DIAS_POR_SEMANA = 7;

// === LIMITES OPERACIONALES ===

var MAX_RECORDATORIOS = 50;
var MAX_PASOS_SECUENCIA = 3;
var MAX_ENTRADAS_HISTORIAL_POR_CARGA = 100;
var DIAS_RETENCION_HISTORIAL = 30;

// === TIMEOUTS Y COOLDOWNS (defaults) ===

var TIMEOUT_BARRIDO_MS = 300000;              // 5 minutos
var COOLDOWN_ALERTA_MS = MS_POR_HORA;         // 1 hora
var INTERVALO_VERIFICACION_RECORDATORIOS_MS = MS_POR_MINUTO;  // 1 minuto
var INTERVALO_VERIFICACION_SECUENCIAS_MS = 15 * MS_POR_MINUTO; // 15 minutos

// === PROCESAMIENTO POR LOTES ===

var LIMITE_LOTE_PROCESAMIENTO = 50;           // Max mensajes por ejecucion GAS
var TAMANO_TANDA_ENVIO = 15;                  // Emails por tanda en envio masivo

// === UMBRALES ALERTAS (defaults) ===

var UMBRAL_SILENCIO_HORAS = 4;
var UMBRAL_ESTANCAMIENTO_HORAS = 24;
var UMBRAL_DOCS_DIAS = 2;
var UMBRAL_URGENCIA_CARGA_HORAS = 3;

// === UMBRALES DASHBOARD ===

var VENTANA_SEMANAL_DIAS = 6;                 // Grafico ultimos 7 dias (0-6)

// === PRESETS TEMPORALES ===

var PRESET_15_MIN = 15;
var PRESET_30_MIN = 30;
var PRESET_1_HORA = 60;
var PRESET_2_HORAS = 120;
var PRESET_4_HORAS = 240;

// === CLAVES STORAGE ===

var STORAGE_KEY_PREFS = 'tabulatorPrefs';

// === HORARIOS ESPECIALES ===

var HORA_MATUTINO_DEFAULT = '08:00';
var HORA_REPORTE_DEFAULT = '18:00';
var HORA_MANANA_DEFAULT = 9;                  // 9:00 AM

// === EXPORTAR ===

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    // Tiempo
    MS_POR_SEGUNDO: MS_POR_SEGUNDO,
    MS_POR_MINUTO: MS_POR_MINUTO,
    MS_POR_HORA: MS_POR_HORA,
    MS_POR_DIA: MS_POR_DIA,
    SEGUNDOS_POR_MINUTO: SEGUNDOS_POR_MINUTO,
    MINUTOS_POR_HORA: MINUTOS_POR_HORA,
    HORAS_POR_DIA: HORAS_POR_DIA,
    DIAS_POR_SEMANA: DIAS_POR_SEMANA,

    // Limites
    MAX_RECORDATORIOS: MAX_RECORDATORIOS,
    MAX_PASOS_SECUENCIA: MAX_PASOS_SECUENCIA,
    MAX_ENTRADAS_HISTORIAL_POR_CARGA: MAX_ENTRADAS_HISTORIAL_POR_CARGA,
    DIAS_RETENCION_HISTORIAL: DIAS_RETENCION_HISTORIAL,

    // Timeouts
    TIMEOUT_BARRIDO_MS: TIMEOUT_BARRIDO_MS,
    COOLDOWN_ALERTA_MS: COOLDOWN_ALERTA_MS,
    INTERVALO_VERIFICACION_RECORDATORIOS_MS: INTERVALO_VERIFICACION_RECORDATORIOS_MS,
    INTERVALO_VERIFICACION_SECUENCIAS_MS: INTERVALO_VERIFICACION_SECUENCIAS_MS,

    // Lotes
    LIMITE_LOTE_PROCESAMIENTO: LIMITE_LOTE_PROCESAMIENTO,
    TAMANO_TANDA_ENVIO: TAMANO_TANDA_ENVIO,

    // Umbrales alertas
    UMBRAL_SILENCIO_HORAS: UMBRAL_SILENCIO_HORAS,
    UMBRAL_ESTANCAMIENTO_HORAS: UMBRAL_ESTANCAMIENTO_HORAS,
    UMBRAL_DOCS_DIAS: UMBRAL_DOCS_DIAS,
    UMBRAL_URGENCIA_CARGA_HORAS: UMBRAL_URGENCIA_CARGA_HORAS,

    // Dashboard
    VENTANA_SEMANAL_DIAS: VENTANA_SEMANAL_DIAS,

    // Presets
    PRESET_15_MIN: PRESET_15_MIN,
    PRESET_30_MIN: PRESET_30_MIN,
    PRESET_1_HORA: PRESET_1_HORA,
    PRESET_2_HORAS: PRESET_2_HORAS,
    PRESET_4_HORAS: PRESET_4_HORAS,

    // Horarios
    HORA_MATUTINO_DEFAULT: HORA_MATUTINO_DEFAULT,
    HORA_REPORTE_DEFAULT: HORA_REPORTE_DEFAULT,
    HORA_MANANA_DEFAULT: HORA_MANANA_DEFAULT,

    // Claves storage
    STORAGE_KEY_PREFS: STORAGE_KEY_PREFS
  };
}
